"""add matches table

Revision ID: 147003fd0feb
Revises: 39eb7db50853
Create Date: 2024-09-08 18:50:20.076353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147003fd0feb'
down_revision: Union[str, None] = '39eb7db50853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('goals_home', sa.Integer(), nullable=False),
    sa.Column('goals_away', sa.Integer(), nullable=False),
    sa.Column('extra_time', sa.Boolean(), nullable=False),
    sa.Column('goals_extra_time_home', sa.Integer(), nullable=True),
    sa.Column('goals_extra_time_away', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Boolean(), nullable=False),
    sa.Column('goals_penalty_home', sa.Integer(), nullable=True),
    sa.Column('goals_penalty_away', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
